import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { Banner } from '../components/banner'
import Card from '../components/card'
import Link from 'next/link'
import Navbar from '../components/navbar'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar/>

      <main className={styles.main}>
        <Banner/>
        <div className={styles.heroImage}>
          <Image src="/assets/heroImage.png" width={300} height={250} />
        </div>
        <div className={styles.cardLayout}>
        <Card className={styles.card} name="Cofee name" href="/coffee-store/newcoffee" imageUrl="/assets/heroImage.jpg"/>
        <Card className={styles.card} name="Cofee name" href="/coffee-store/newcoffee" imageUrl="/assets/heroImage.jpg"/>
        <Card className={styles.card} name="Cofee name" href="/coffee-store/newcoffee" imageUrl="/assets/heroImage.jpg"/>
        </div>
      </main>

    </div>
  )
}
